spring:
  datasource:
    url: jdbc:h2:mem://localhost/~/instagram;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

fcm:
  key:
    path: push-8c2a6-firebase-adminsdk-5kzfd-bc11bea218.json

logging:
  level:
#    root: debug
    org:
      hibernate:
        SQL: debug
        type: trace